### ISSUE TITLE
Link generating issue.

### ISSUE THREAD

**Issue by jarmy1525** [Cyber-Anonymous/Dark-Phish#3]
Link is not generated.  Please see the provided screenshot ahmnd help to resolve this issue.
![IMG_20220804_103817](https://user-images.githubusercontent.com/102465196/182767888-3dd1bf1b-947c-4d5a-9fc9-fd222db653f6.JPG)

**Comment by etame20** [comment]
Please how to install python3 to termux

**Comment by Salahsallu** [comment]
how to generate link

**Comment by priteshkumar87** [comment]
Link not showing 
![Uploading Screenshot_20230826_210207_com.termux.jpg…]()
